### ISSUE TITLE
CPU/GPU compute nodes on HPCs sometimes don't have internet access

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#64]
I am trying out the regional OMIP from #49 and I am running into the following issue. The GPU/CPU compute nodes on Australia's HPC don't have internet access. In order to run the experiment I first need to run on a login node so that package is instantiated, deps are installed, and initial conditions, etc are downloaded. Only after I can run on the GPU node. Is there a way to streamline this for people? I presume this is not something that only happens on Australia's HPC but I'm not really sure tbh.

**Comment by navidcy** [comment]
Ideally, we want to be able to run something on the login node that would prepare the data (eg download everything etc). This should be, ideally, something not very heavy memory-wise. E.g., when I tried to change `GPU() -> CPU()` and just run the `regional_omip_simulation.jl` in the login node the job was killed since it exceeded the memory limit that the login node has (since supposedly the login node is not for doing computations...)

**Comment by glwagner** [comment]
Yes, the data is downloaded by calling `ecco2_field` (for T, S, and eventually ice thickness) and `JRA55_prescribed_atmosphere` (which downloads relevant JRA55 data). The rest of the lines run the model.

Arguments passed to `JRA55_prescribed_atmosphere` control behavior so you can limit the amount of the dataset that is loaded into memory.

It's a work in progress right now because we currently download the `.nc` files, then we have to build `jld2` files in order to use `FieldTimeSeries`. Building the `.jld2` files takes a while. Ideally we will upload the `.jld2` files and download those directly as needed.

**Comment by glwagner** [comment]
This issue is quite specific to #49 so we may want to discuss over there

**Comment by navidcy** [comment]
okie
